server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.200.111:3100/loki/api/v1/push

scrape_configs:
  - job_name: audit_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: audit_log
          __path__: /mnt/logs/audit.jsonl
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            guild_id: guild_id
            channel_id: channel_id
            message_id: message_id
            user_id: user_id
            user_name: user_name
            event_type: event_type
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          guild_id:
          channel_id:
          user_id:
          user_name:
          event_type:
